### ISSUE TITLE
Error when validating signing key

### ISSUE THREAD

**Issue by OlegOLK** [blockstack-radiks/radiks-server#11]
Hi @hstove  you have created an amazing service!

Unfortunately, while using radiks-server with radiks I start to experience strange behavior:
`await userSession.handlePendingSignIn();
 await User.createWithCurrentUser();`

as far as I understand the last line of code trying to fetch user from mongo with help of current user id, unfortunately, something changed and this method isn't working correctly right now.

Exception from radiks-server

`(node:34832) UnhandledPromiseRejectionWarning: Error: Error when validating: No signing key is present with id: '[object Object]'
    at errorMessage (\AppData\Roaming\npm\node_modules\radiks-server\app\lib\validator.js:4:9)
    at Validator.validateSignature (\AppData\Roaming\npm\node_modules\radiks-server\app\lib\validator.js:47:9)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:34832) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)`

**Comment by OlegOLK** [comment]
@pradel I sorry for bothering you (saw you in recent PR's) maybe you know the root cause of this issue?

**Comment by pradel** [comment]
I never noticed this issue before but I am doing like this to identify the users:
```ts
if (userSession.isSignInPending()) {
      await userSession.handlePendingSignIn();
      await RadiksUser.createWithCurrentUser();
    }
```

You can take a look at the `next` branch for sigle it's working there (all the code is inside the server and client folders) :) https://github.com/pradel/sigle/tree/next
