### ISSUE TITLE
Apply validation rules before saving models

### ISSUE THREAD

**Issue by friedger** [blockstack-radiks/radiks-server#12]
Models should allow to specify validation rules, like {range:1..5} for integers, {isSigingUser} for usernames.

These rules should be validated before saving an object.

**Comment by pradel** [comment]
Would be great to be able to execute custom functions for the models on the server 👍

**Comment by hstove** [comment]
I am in favor of doing this in the way that is described in the Radiks decentralization proposal - this would have less reliance on custom server code, and include validation that other servers could validate.

https://forum.blockstack.org/t/radiks-decentralization-proposal/8400
