### ISSUE TITLE
Working with Gaia

### ISSUE THREAD

**Issue by theallegrarr** [blockstack-radiks/radiks-server#27]
Please is there any resource for gathering data stored in gaia using radiks
for example if i have 100 posts stored in 20 different users gaia hub, how do i fetch all of them using gaia

and also any basic gaia+radiks setup guide

**Comment by hstove** [comment]
Radiks uses Gaia out of the box! If you build your app with Radiks, you'll be able to do exactly what you're hoping to do. If you already have data in Gaia, but not using Radiks, then you'll have to migrate your app to use Radiks.

For a guide, checkout the README in this repository.
